### ISSUE TITLE
Installation issue - Uncaught TypeError: Cannot read properties of undefined 'toLocaleString'

### ISSUE THREAD

**Issue by mrodriguez2** [steel-dev/steel-browser#11]
Hey,

I wanted to try it out but unfortunately I'm having installation issues.

I followed the steps:

```
git clone https://github.com/steel-dev/steel-browser
cd steel-browser
npm install
npm run dev
```

This outputs:

```
> steel@1.0.0 dev
> concurrently "npm run dev:api" "npm run dev:ui"

[1] 
[1] > steel@1.0.0 dev:ui
[1] > cd ui && npm run dev
[1] 
[0] 
[0] > steel@1.0.0 dev:api
[0] > cd api && npm run dev
[0] 
[0] 
[0] > steel-browser@1.0.0 dev
[0] > ts-node-dev --poll --exit-child ./src/index.ts
[0] 
[1] 
[1] > @steel/ui@0.0.0 dev
[1] > vite --host 0.0.0.0
[1] 
[1] 
[1]   VITE v4.5.5  ready in 110 ms
[1] 
[1]   ➜  Local:   http://localhost:5173/
[1]   ➜  Network: http://192.168.1.88:5173/
[0] [INFO] 17:42:06 ts-node-dev ver. 2.0.0 (using ts-node ver. 10.9.2, typescript ver. 5.5.4)
[0] Extensions directory does not exist
[0] Launch args [
[0]   '--remote-allow-origins=*',
[0]   '--disable-dev-shm-usage',
[0]   '--disable-gpu',
[0]   '--start-maximized',
[0]   '--remote-debugging-address=127.0.0.1',
[0]   '--remote-debugging-port=9222',
[0]   '--no-sandbox',
[0]   '--disable-setuid-sandbox',
[0]   '--use-angle=disabled',
[0]   '--disable-blink-features=AutomationControlled',
[0]   '--disable-software-rasterizer',
[0]   '--window-size=1920,1080',
[0]   '--timezone=America/New_York'
[0] ]

```

Which looks good at first, but if I go to over to localhost:5173, I get:

<img width="1910" alt="Screenshot 2024-11-28 at 17 46 46" src="https://github.com/user-attachments/assets/4056df59-aa5c-4721-ad77-81a2cc26f5d7">

If I go the Docker route, I get a different error:

```
Starting Xvfb...
Starting nginx...
Starting API service...
Starting UI service...
All services started. Keeping container alive...

> @steel/ui@0.0.0 start
> serve dist -l 5173


> steel-browser@1.0.0 start
> node ./build/index.js

 INFO  Accepting connections at http://localhost:5173
Extensions directory does not exist
Launch args [
  '--remote-allow-origins=*',
  '--disable-dev-shm-usage',
  '--disable-gpu',
  '--start-maximized',
  '--remote-debugging-address=127.0.0.1',
  '--remote-debugging-port=9222',
  '--no-sandbox',
  '--disable-setuid-sandbox',
  '--use-angle=disabled',
  '--disable-blink-features=AutomationControlled',
  '--disable-software-rasterizer',
  '--window-size=1920,1080',
  '--timezone=America/New_York'
]
/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72
            this._reject(callback, new Errors_js_1.TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
    at CallbackRegistry.clear (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72:36)
    at #onClose (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:164:25)
    at WebSocket.<anonymous> (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
    at callListener (/app/api/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/app/api/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:518:28)
    at WebSocket.emitClose (/app/api/node_modules/ws/lib/websocket.js:272:10)
    at Socket.socketOnClose (/app/api/node_modules/ws/lib/websocket.js:1341:15)
    at Socket.emit (node:events:518:28)
    at TCP.<anonymous> (node:net:337:12) {
  cause: ProtocolError
      at <instance_members_initializer> (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
      at new Callback (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
      at CallbackRegistry.create (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
      at Connection._rawSend (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
      at Connection.send (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:21)
      at ChromeTargetManager.initialize (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ChromeTargetManager.js:96:32)
      at async CdpBrowser._attach (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:72:9)
      at async CdpBrowser._create (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:27:9)
      at async ChromeLauncher.launch (/app/api/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:140:31)
      at async CDPService.launch (/app/api/build/services/cdp.service.js:398:33)
}

Node.js v20.12.0
npm notice 
npm notice New minor version of npm available! 10.5.0 -> 10.9.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.9.1>
npm notice Run `npm install -g npm@10.9.1` to update!
npm notice 
```

I'm on MacOS, Chrome executable in the right path and Node installed. What am I doing wrong?

**Comment by fukouda** [comment]
Hey! Sorry, I should have added this to the readme, but in the ui folder there is an `env.local.example`, copy that to an `env.local` file or `.env` and you should be good. It just doesn't know what API endpoint to point to otherwise.

Will update this to make it more clear/easier

**Comment by mrodriguez2** [comment]
Thanks for the quick response!

I renamed the file to .env.local and did the Docker process again. Output looks good:

```
docker run -p 3000:3000 -p 5173:5173 -p 9223:9223 steel

> @steel/ui@0.0.0 start
> serve dist -l 5173

 INFO  Accepting connections at http://localhost:5173
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 GET /
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 Returned 304 in 17 ms
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 GET /assets/index-764c4543.js
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 GET /assets/index-6acb7367.css
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 Returned 304 in 6 ms
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 Returned 304 in 7 ms
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 GET /assets/Geist-Regular-0dceeee4.otf
 HTTP  11/28/2024 5:10:55 PM 192.168.65.1 Returned 304 in 2 ms
 HTTP  11/28/2024 5:11:19 PM 192.168.65.1 GET /assets/index-6acb7367.css
 HTTP  11/28/2024 5:11:19 PM 192.168.65.1 Returned 304 in 1 ms

```
However, if I go to the UI at http://localhost:5173/ I simply get a black screen and the following error:

<img width="1910" alt="Screenshot 2024-11-28 at 18 11 29" src="https://github.com/user-attachments/assets/dcee56a8-13a4-4459-822c-4be592c422af">

Loading `localhost:3000` gives a unreachable error. What did I miss?

Repeating the process with Node directly (npm run dev) does get me a bit further (Chrome loads and no errors are shown) but executing:

```

curl -X POST http://0.0.0.0:3000/scrape \
  -H "Content-Type: application/json" \
  -d '{
    "url": "https://example.com",
    "waitFor": 1000
  }'
```

gives back:

`{"message":"Route POST:/scrape not found","error":"Not Found","statusCode":404}
`

Thanks!

**Comment by fukouda** [comment]
Hey @mrodriguez2 , issue was closed after merging this PR, but lmk if you are still facing issues here --- I updated the docs to reflect the endpoint changes (from `/scrape` to `/v1/scrape` for example) and ignored the env.local in the docker build so it should point to localhost:3000 when running from docker and 0.0.0.0:3000 when running locally (using npm)
