### ISSUE TITLE
Chrome initialization failure in docker setup - M2 Mac 

### ISSUE THREAD

**Issue by saxenauts** [steel-dev/steel-browser#33]
Environment:
Host: Apple Silicon M2 Pro, macOS 15.1.1
Docker: linux/amd64 platform
Chrome: Version 128.0.6613.119
Node.js: v20.12.0

Consistent Failure Indicators:
QEMU signal traps
GPU process initialization failure
CDP target closure
Chrome starts and crashes 

I am trying to set this up with docker compose build --no-cache && docker compose up -d

Here's the error I get (with fresh setup, no code changes on my end)

```
➜  ~ docker logs -f steel-browser-api-1
Starting nginx...
Starting dbus...
Starting Xvfb...

> steel-browser@1.0.0 start
> node ./build/index.js

Launch args [
  '--remote-allow-origins=*',
  '--disable-dev-shm-usage',
  '--disable-gpu',
  '--start-maximized',
  '--remote-debugging-address=127.0.0.1',
  '--remote-debugging-port=9222',
  '--no-sandbox',
  '--disable-setuid-sandbox',
  '--use-angle=disabled',
  '--disable-blink-features=AutomationControlled',
  '--disable-software-rasterizer',
  '--unsafely-treat-insecure-origin-as-secure=http://0.0.0.0:3000,http://localhost:3000',
  '--window-size=1920,1080',
  '--timezone=America/New_York',
  '--load-extension=/app/extensions/recorder',
  '--disable-extensions-except=/app/extensions/recorder'
]
/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72
            this._reject(callback, new Errors_js_1.TargetCloseError('Target closed'));
                                   ^

TargetCloseError: Protocol error (Target.setAutoAttach): Target closed
    at CallbackRegistry.clear (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:72:36)
    at #onClose (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:164:25)
    at WebSocket.<anonymous> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:49:30)
    at callListener (/app/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onClose (/app/node_modules/ws/lib/event-target.js:220:9)
    at WebSocket.emit (node:events:518:28)
    at WebSocket.emitClose (/app/node_modules/ws/lib/websocket.js:272:10)
    at Socket.socketOnClose (/app/node_modules/ws/lib/websocket.js:1341:15)
    at Socket.emit (node:events:518:28)
    at TCP.<anonymous> (node:net:337:12) {
  cause: ProtocolError
      at <instance_members_initializer> (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:93:14)
      at new Callback (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:97:16)
      at CallbackRegistry.create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/common/CallbackRegistry.js:22:26)
      at Connection._rawSend (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:89:26)
      at Connection.send (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:80:21)
      at ChromeTargetManager.initialize (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/ChromeTargetManager.js:96:32)
      at async CdpBrowser._attach (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:72:9)
      at async CdpBrowser._create (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Browser.js:27:9)
      at async ChromeLauncher.launch (/app/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:140:31)
      at async CDPService.launch (/app/build/services/cdp.service.js:335:33)
}

Node.js v20.12.0
npm notice 
npm notice New major version of npm available! 10.5.0 -> 11.0.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v11.0.0>
npm notice Run `npm install -g npm@11.0.0` to update!
npm notice 
```

I tried to debug it myself, like I had mentioned on discord server.

- Verified Xvfb, DBus, and display settings.
- Cleaned up environment variables
- Added verbose logging to launch process

Got these errors, pointing to QEMU and GPU setup failure

```
   qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
   [106:106:1221/174727.421705:ERROR:browser_dm_token_storage_linux.cc(105)] Error: /etc/machine-id contains 0 characters (32 were expected).
```
I added that file too in the docker setup

```
dbus-uuidgen --ensure=/etc/machine-id
```

GPU issue
```
   [106:106:1221/174730.804500:FATAL:gpu_data_manager_impl_private.cc(436)] GPU process isn't usable. Goodbye.
   [1221/174730.807476:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)   
```

I had somehow managed to make this work yesterday night, got too cocky, didn't document and decided to do a fresh install again today. 

By this point, it was going beyond my skill level, and I could use my time better so I am going to just work with node server and make my own docker service to test with my app. Maybe it's specific to my machine.

**Comment by fukouda** [comment]
hey @saxenauts , thanks for going so deep and laying out everything you've tried. So, we ran into this issue before when we were running Chromium instead of Chrome but it went away once we switched (still not sure why). For this, there are a couple chrome flags that might get the error to go away, but could potentially affect performance: https://peter.sh/experiments/chromium-command-line-switches/

I remember trying a bunch but `--in-process-gpu` seems familiar (in place of disable-gpu). This issue is definitely more common when running the image in emulation mode on an M chip Mac (hence the QEMU errors). If you have some time, I would love to hop on a call with you and debug a little further -- feel free to bug me on our [discord server](https://discord.com/invite/steel-dev).

Also, I'm assuming you're using Docker Desktop but a couple of our users have found success running the Docker image through the docker engine created by [OrbStack](https://orbstack.dev/). Perhaps they handle emulation better? Either way, keep me in the loop with what you try and if you manage to get it running again, I will try to get a deeper understanding of why this is happening for the time being 🙏
